// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4qj-1D5APD4N2Risu487RzrziX99MCI',
    appId: '1:228103071479:web:40481fb37a5924b56415f2',
    messagingSenderId: '228103071479',
    projectId: 'miniproject-c03ff',
    authDomain: 'miniproject-c03ff.firebaseapp.com',
    databaseURL: 'https://miniproject-c03ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'miniproject-c03ff.firebasestorage.app',
    measurementId: 'G-LMJJ8P7PES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUaScRumUjLN75ZDmAuyzxl4z9wknFJbQ',
    appId: '1:228103071479:android:db089acf57aa8b416415f2',
    messagingSenderId: '228103071479',
    projectId: 'miniproject-c03ff',
    databaseURL: 'https://miniproject-c03ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'miniproject-c03ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_N9wVVV1e6v5fayOO4mlXccaof-RSBQ',
    appId: '1:228103071479:ios:2f41f721a963656a6415f2',
    messagingSenderId: '228103071479',
    projectId: 'miniproject-c03ff',
    databaseURL: 'https://miniproject-c03ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'miniproject-c03ff.appspot.com', // Corrected from firebasestorage.app
    iosBundleId: 'com.example.miniproject',
  );
}